AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/schema.rb'
    - 'db/*/**'
    - 'vendor/*/**'

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 130

Style/BlockDelimiters:
  Exclude:
    - 'spec/*/**'

Metrics/BlockLength:
  Exclude:
    - 'spec/*/**'

