language: ruby
rvm:
  - 2.4
env:
  - DB=postgres
addons:
  postgresql: '9.4'
script:
  - bundle install
  - RAILS_ENV=test bundle exec rake db:create db:migrate db:test:prepare
  - bundle exec rspec && bundle exec rubocop
